/**
 * Spring Boot REST API
 * Language Management REST API
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: techshard08@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Cours } from './cours';
import { User } from './user';


export interface Commentaire {
    afficheBooleen?: boolean;
    commentaireId?: number;
    commentaireUtile?: number;
    cours?: Cours;
    texteCommentaire?: string;
    titreCommentaire?: string;
    user?: User;
}
