/**
 * Spring Boot REST API
 * Language Management REST API
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: techshard08@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Categorie } from './categorie';
import { Progression } from './progression';
import { Question } from './question';


export interface Cours {
    categorie?: Categorie;
    coursId?: number;
    image?: string;
    lienMarchand?: string;
    progressions?: Array<Progression>;
    questions?: Array<Question>;
    texte?: string;
    titre?: string;
    video?: string;
}
