/**
 * Spring Boot REST API
 * Language Management REST API
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * Contact: techshard08@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategorieDto } from './categorieDto';
import { CommentaireDto } from './commentaireDto';
import { ProgressionDto } from './progressionDto';


export interface CoursDto {
    categorie?: CategorieDto;
    commentaires?: Array<CommentaireDto>;
    coursId?: number;
    difficulte?: number;
    image?: string;
    lienMarchand?: string;
    progressions?: Array<ProgressionDto>;
    texte?: string;
    titre?: string;
    video?: string;
}
